"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class IpfsFileInfoTypedDict(TypedDict):
    cid: str
    r"""CID of the file on IPFS"""
    url: NotRequired[str]
    r"""URL with IPFS scheme for the file"""
    gateway_url: NotRequired[str]
    r"""URL to access file via HTTP through an IPFS gateway"""


class IpfsFileInfo(BaseModel):
    cid: str
    r"""CID of the file on IPFS"""

    url: Optional[str] = None
    r"""URL with IPFS scheme for the file"""

    gateway_url: Annotated[Optional[str], pydantic.Field(alias="gatewayUrl")] = None
    r"""URL to access file via HTTP through an IPFS gateway"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["url", "gatewayUrl"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
