"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class LiveVideoToVideoResponseTypedDict(TypedDict):
    r"""Response model for live video-to-video generation."""

    subscribe_url: str
    r"""Source URL of the incoming stream to subscribe to"""
    publish_url: str
    r"""Destination URL of the outgoing stream to publish to"""
    control_url: NotRequired[str]
    r"""URL for updating the live video-to-video generation"""
    events_url: NotRequired[str]
    r"""URL for subscribing to events for pipeline status and logs"""
    request_id: NotRequired[str]
    r"""The ID generated for this request"""
    manifest_id: NotRequired[str]
    r"""Orchestrator manifest ID for this request"""


class LiveVideoToVideoResponse(BaseModel):
    r"""Response model for live video-to-video generation."""

    subscribe_url: str
    r"""Source URL of the incoming stream to subscribe to"""

    publish_url: str
    r"""Destination URL of the outgoing stream to publish to"""

    control_url: Optional[str] = ""
    r"""URL for updating the live video-to-video generation"""

    events_url: Optional[str] = ""
    r"""URL for subscribing to events for pipeline status and logs"""

    request_id: Optional[str] = ""
    r"""The ID generated for this request"""

    manifest_id: Optional[str] = ""
    r"""Orchestrator manifest ID for this request"""
