"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class LiveVideoToVideoParamsParamsTypedDict(TypedDict):
    r"""Initial parameters for the pipeline."""


class LiveVideoToVideoParamsParams(BaseModel):
    r"""Initial parameters for the pipeline."""


class LiveVideoToVideoParamsTypedDict(TypedDict):
    subscribe_url: str
    r"""Source URL of the incoming stream to subscribe to."""
    publish_url: str
    r"""Destination URL of the outgoing stream to publish."""
    control_url: NotRequired[str]
    r"""URL for subscribing via Trickle protocol for updates in the live video-to-video generation params."""
    events_url: NotRequired[str]
    r"""URL for publishing events via Trickle protocol for pipeline status and logs."""
    model_id: NotRequired[str]
    r"""Name of the pipeline to run in the live video to video job. Notice that this is named model_id for consistency with other routes, but it does not refer to a Hugging Face model ID. The exact model(s) depends on the pipeline implementation and might be configurable via the `params` argument."""
    params: NotRequired[LiveVideoToVideoParamsParamsTypedDict]
    r"""Initial parameters for the pipeline."""
    gateway_request_id: NotRequired[str]
    r"""The ID of the Gateway request (for logging purposes)."""
    manifest_id: NotRequired[str]
    r"""The manifest ID from the orchestrator (for logging purposes)."""
    stream_id: NotRequired[str]
    r"""The Stream ID (for logging purposes)."""


class LiveVideoToVideoParams(BaseModel):
    subscribe_url: str
    r"""Source URL of the incoming stream to subscribe to."""

    publish_url: str
    r"""Destination URL of the outgoing stream to publish."""

    control_url: Optional[str] = ""
    r"""URL for subscribing via Trickle protocol for updates in the live video-to-video generation params."""

    events_url: Optional[str] = ""
    r"""URL for publishing events via Trickle protocol for pipeline status and logs."""

    model_id: Optional[str] = ""
    r"""Name of the pipeline to run in the live video to video job. Notice that this is named model_id for consistency with other routes, but it does not refer to a Hugging Face model ID. The exact model(s) depends on the pipeline implementation and might be configurable via the `params` argument."""

    params: Optional[LiveVideoToVideoParamsParams] = None
    r"""Initial parameters for the pipeline."""

    gateway_request_id: Optional[str] = ""
    r"""The ID of the Gateway request (for logging purposes)."""

    manifest_id: Optional[str] = ""
    r"""The manifest ID from the orchestrator (for logging purposes)."""

    stream_id: Optional[str] = ""
    r"""The Stream ID (for logging purposes)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "control_url",
                "events_url",
                "model_id",
                "params",
                "gateway_request_id",
                "manifest_id",
                "stream_id",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
