"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .llmmessage import LLMMessage, LLMMessageTypedDict
from livepeer.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class LLMChoiceTypedDict(TypedDict):
    index: int
    finish_reason: NotRequired[str]
    delta: NotRequired[LLMMessageTypedDict]
    message: NotRequired[LLMMessageTypedDict]


class LLMChoice(BaseModel):
    index: int

    finish_reason: Optional[str] = ""

    delta: Optional[LLMMessage] = None

    message: Optional[LLMMessage] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["finish_reason", "delta", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
