"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .attestation import Attestation
from .playback_policy import PlaybackPolicy
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from livepeer import utils
from typing import List, Optional


class PlaybackInfoType(str, Enum):
    LIVE = 'live'
    VOD = 'vod'
    RECORDING = 'recording'


class Live(int, Enum):
    ZERO = 0
    ONE = 1


class Hrn(str, Enum):
    r"""Human Readable Name"""
    HLS_TS_ = 'HLS (TS)'
    MP4 = 'MP4'
    WEB_RTC_H264_ = 'WebRTC (H264)'
    FLV_H264_ = 'FLV (H264)'
    THUMBNAIL_JPEG_ = 'Thumbnail (JPEG)'
    THUMBNAILS = 'Thumbnails'


class PlaybackInfoMetaType(str, Enum):
    HTML5_APPLICATION_VND_APPLE_MPEGURL = 'html5/application/vnd.apple.mpegurl'
    HTML5_VIDEO_MP4 = 'html5/video/mp4'
    HTML5_VIDEO_H264 = 'html5/video/h264'
    VIDEO_X_FLV = 'video/x-flv'
    IMAGE_JPEG = 'image/jpeg'
    TEXT_VTT = 'text/vtt'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PlaybackInfoSource:
    hrn: Hrn = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('hrn') }})
    r"""Human Readable Name"""
    type: PlaybackInfoMetaType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    url: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('url') }})
    size: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('size'), 'exclude': lambda f: f is None }})
    width: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('width'), 'exclude': lambda f: f is None }})
    height: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('height'), 'exclude': lambda f: f is None }})
    bitrate: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('bitrate'), 'exclude': lambda f: f is None }})
    



class PlaybackInfoHrn(str, Enum):
    HLS_TS_ = 'HLS (TS)'


class PlaybackInfoMetaDvrPlaybackType(str, Enum):
    HTML5_APPLICATION_VND_APPLE_MPEGURL = 'html5/application/vnd.apple.mpegurl'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class DvrPlayback:
    hrn: Optional[PlaybackInfoHrn] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('hrn'), 'exclude': lambda f: f is None }})
    type: Optional[PlaybackInfoMetaDvrPlaybackType] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type'), 'exclude': lambda f: f is None }})
    url: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('url'), 'exclude': lambda f: f is None }})
    error: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('error'), 'exclude': lambda f: f is None }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Meta:
    UNSET='__SPEAKEASY_UNSET__'
    source: List[PlaybackInfoSource] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('source') }})
    live: Optional[Live] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('live'), 'exclude': lambda f: f is None }})
    playback_policy: Optional[PlaybackPolicy] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('playbackPolicy'), 'exclude': lambda f: f is Meta.UNSET }})
    r"""Whether the playback policy for an asset or stream is public or signed"""
    dvr_playback: Optional[List[DvrPlayback]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('dvrPlayback'), 'exclude': lambda f: f is None }})
    attestation: Optional[Attestation] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('attestation'), 'exclude': lambda f: f is None }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PlaybackInfo:
    type: PlaybackInfoType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    meta: Meta = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('meta') }})
    

