"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer.types import BaseModel
import pydantic
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class TargetOutputTypedDict(TypedDict):
    profile: str
    r"""Name of transcoding profile that should be sent. Use
    \"source\" for pushing source stream data

    """
    video_only: NotRequired[bool]
    r"""If true, the stream audio will be muted and only silent
    video will be pushed to the target.

    """
    id: NotRequired[str]
    r"""ID of multistream target object where to push this stream"""


class TargetOutput(BaseModel):
    profile: str
    r"""Name of transcoding profile that should be sent. Use
    \"source\" for pushing source stream data

    """

    video_only: Annotated[Optional[bool], pydantic.Field(alias="videoOnly")] = False
    r"""If true, the stream audio will be muted and only silent
    video will be pushed to the target.

    """

    id: Optional[str] = None
    r"""ID of multistream target object where to push this stream"""
