"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from typing import List, Union

UserTags3 = Union[str, float]

UserTags = Union[str, float, List['UserTags3']]
