"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from sdk import utils
from typing import Optional

class Phase(str, Enum):
    r"""Phase of the asset storage"""
    WAITING = 'waiting'
    PROCESSING = 'processing'
    READY = 'ready'
    FAILED = 'failed'
    REVERTED = 'reverted'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Tasks:
    failed: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('failed'), 'exclude': lambda f: f is None }})
    r"""ID of the last task to fail execution."""
    last: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('last'), 'exclude': lambda f: f is None }})
    r"""ID of the last task to run successfully, that created
    the currently saved data.
    """
    pending: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('pending'), 'exclude': lambda f: f is None }})
    r"""ID of any currently running task that is exporting this
    asset to IPFS.
    """
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class StorageStatus:
    phase: Phase = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('phase') }})
    r"""Phase of the asset storage"""
    tasks: Tasks = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('tasks') }})
    error_message: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('errorMessage'), 'exclude': lambda f: f is None }})
    r"""Error message if the last storage changed failed."""
    progress: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('progress'), 'exclude': lambda f: f is None }})
    r"""Current progress of the task updating the storage."""
    

