"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .httperror import HTTPErrorData
from .httpvalidationerror import HTTPValidationErrorData
from .studio_api_error import StudioAPIErrorData
from dataclasses import dataclass, field
import httpx
from livepeer.models.errors import LivepeerError
from typing import Optional, Union
from typing_extensions import TypeAliasType


GenAudioToTextGenerateResponse500ResponseBodyUnion = TypeAliasType(
    "GenAudioToTextGenerateResponse500ResponseBodyUnion",
    Union[HTTPErrorData, StudioAPIErrorData],
)
r"""Internal Server Error"""


@dataclass(frozen=True)
class GenAudioToTextGenerateResponse500ResponseBody(LivepeerError):
    r"""Internal Server Error"""

    data: GenAudioToTextGenerateResponse500ResponseBodyUnion = field(hash=False)

    def __init__(
        self,
        data: GenAudioToTextGenerateResponse500ResponseBodyUnion,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


GenAudioToTextGenerateResponse422ResponseBodyUnion = TypeAliasType(
    "GenAudioToTextGenerateResponse422ResponseBodyUnion",
    Union[HTTPValidationErrorData, StudioAPIErrorData],
)
r"""Validation Error"""


@dataclass(frozen=True)
class GenAudioToTextGenerateResponse422ResponseBody(LivepeerError):
    r"""Validation Error"""

    data: GenAudioToTextGenerateResponse422ResponseBodyUnion = field(hash=False)

    def __init__(
        self,
        data: GenAudioToTextGenerateResponse422ResponseBodyUnion,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


GenAudioToTextGenerateResponse415ResponseBodyUnion = TypeAliasType(
    "GenAudioToTextGenerateResponse415ResponseBodyUnion",
    Union[HTTPErrorData, StudioAPIErrorData],
)
r"""Unsupported Media Type"""


@dataclass(frozen=True)
class GenAudioToTextGenerateResponse415ResponseBody(LivepeerError):
    r"""Unsupported Media Type"""

    data: GenAudioToTextGenerateResponse415ResponseBodyUnion = field(hash=False)

    def __init__(
        self,
        data: GenAudioToTextGenerateResponse415ResponseBodyUnion,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


GenAudioToTextGenerateResponseResponseBodyUnion = TypeAliasType(
    "GenAudioToTextGenerateResponseResponseBodyUnion",
    Union[HTTPErrorData, StudioAPIErrorData],
)
r"""Request Entity Too Large"""


@dataclass(frozen=True)
class GenAudioToTextGenerateResponseResponseBody(LivepeerError):
    r"""Request Entity Too Large"""

    data: GenAudioToTextGenerateResponseResponseBodyUnion = field(hash=False)

    def __init__(
        self,
        data: GenAudioToTextGenerateResponseResponseBodyUnion,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


GenAudioToTextGenerateResponseBodyUnion = TypeAliasType(
    "GenAudioToTextGenerateResponseBodyUnion", Union[HTTPErrorData, StudioAPIErrorData]
)
r"""Unauthorized"""


@dataclass(frozen=True)
class GenAudioToTextGenerateResponseBody(LivepeerError):
    r"""Unauthorized"""

    data: GenAudioToTextGenerateResponseBodyUnion = field(hash=False)

    def __init__(
        self,
        data: GenAudioToTextGenerateResponseBodyUnion,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


GenAudioToTextResponseBodyUnion = TypeAliasType(
    "GenAudioToTextResponseBodyUnion", Union[HTTPErrorData, StudioAPIErrorData]
)
r"""Bad Request"""


@dataclass(frozen=True)
class GenAudioToTextResponseBody(LivepeerError):
    r"""Bad Request"""

    data: GenAudioToTextResponseBodyUnion = field(hash=False)

    def __init__(
        self,
        data: GenAudioToTextResponseBodyUnion,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
