"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .httperror import HTTPErrorData
from .httpvalidationerror import HTTPValidationErrorData
from .studio_api_error import StudioAPIErrorData
from livepeer import utils
from typing import Union


GenTextToImageGenerateResponse500ResponseBodyUnion = Union[
    HTTPErrorData, StudioAPIErrorData
]
r"""Internal Server Error"""


class GenTextToImageGenerateResponse500ResponseBody(Exception):
    r"""Internal Server Error"""

    data: GenTextToImageGenerateResponse500ResponseBodyUnion

    def __init__(self, data: GenTextToImageGenerateResponse500ResponseBodyUnion):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, GenTextToImageGenerateResponse500ResponseBodyUnion
        )


GenTextToImageGenerateResponseResponseBodyUnion = Union[
    HTTPValidationErrorData, StudioAPIErrorData
]
r"""Validation Error"""


class GenTextToImageGenerateResponseResponseBody(Exception):
    r"""Validation Error"""

    data: GenTextToImageGenerateResponseResponseBodyUnion

    def __init__(self, data: GenTextToImageGenerateResponseResponseBodyUnion):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, GenTextToImageGenerateResponseResponseBodyUnion
        )


GenTextToImageGenerateResponseBodyUnion = Union[HTTPErrorData, StudioAPIErrorData]
r"""Unauthorized"""


class GenTextToImageGenerateResponseBody(Exception):
    r"""Unauthorized"""

    data: GenTextToImageGenerateResponseBodyUnion

    def __init__(self, data: GenTextToImageGenerateResponseBodyUnion):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, GenTextToImageGenerateResponseBodyUnion)


GenTextToImageResponseBodyUnion = Union[HTTPErrorData, StudioAPIErrorData]
r"""Bad Request"""


class GenTextToImageResponseBody(Exception):
    r"""Bad Request"""

    data: GenTextToImageResponseBodyUnion

    def __init__(self, data: GenTextToImageResponseBodyUnion):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, GenTextToImageResponseBodyUnion)
