"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from livepeer.models.components import (
    apierror as components_apierror,
    httpmetadata as components_httpmetadata,
)
from livepeer.models.errors import LivepeerError
from livepeer.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated


class HTTPErrorData(BaseModel):
    detail: components_apierror.APIError
    r"""Detailed error information."""

    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None


@dataclass(unsafe_hash=True)
class HTTPError(LivepeerError):
    r"""HTTP error response model."""

    data: HTTPErrorData = field(hash=False)

    def __init__(
        self,
        data: HTTPErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
