"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer.models.components import (
    error as components_error,
    httpmetadata as components_httpmetadata,
    webhook_input as components_webhook_input,
)
from livepeer.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateWebhookResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    webhook: NotRequired[components_webhook_input.WebhookTypedDict]
    r"""Success"""
    error: NotRequired[components_error.ErrorTypedDict]
    r"""Error"""


class CreateWebhookResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    webhook: Optional[components_webhook_input.Webhook] = None
    r"""Success"""

    error: Optional[components_error.Error] = None
    r"""Error"""
