"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer.models.components import (
    create_room_response as components_create_room_response,
    error as components_error,
    httpmetadata as components_httpmetadata,
)
from livepeer.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateRoomResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    create_room_response: NotRequired[
        components_create_room_response.CreateRoomResponseTypedDict
    ]
    r"""Success"""
    error: NotRequired[components_error.ErrorTypedDict]
    r"""Error"""


class CreateRoomResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    create_room_response: Optional[
        components_create_room_response.CreateRoomResponse
    ] = None
    r"""Success"""

    error: Optional[components_error.Error] = None
    r"""Error"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["create-room-response", "error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
