"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer.models.components import (
    error as components_error,
    httpmetadata as components_httpmetadata,
    stream as components_stream,
)
from livepeer.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateStreamResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    stream: NotRequired[components_stream.StreamTypedDict]
    r"""Success"""
    error: NotRequired[components_error.ErrorTypedDict]
    r"""Error"""


class CreateStreamResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    stream: Optional[components_stream.Stream] = None
    r"""Success"""

    error: Optional[components_error.Error] = None
    r"""Error"""
