"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer.models.components import (
    httpmetadata as components_httpmetadata,
    imageresponse as components_imageresponse,
    studio_api_error as components_studio_api_error,
)
from livepeer.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GenTextToImageResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    image_response: NotRequired[components_imageresponse.ImageResponseTypedDict]
    r"""Successful Response"""
    studio_api_error: NotRequired[components_studio_api_error.StudioAPIErrorTypedDict]
    r"""Error"""


class GenTextToImageResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    image_response: Optional[components_imageresponse.ImageResponse] = None
    r"""Successful Response"""

    studio_api_error: Optional[components_studio_api_error.StudioAPIError] = None
    r"""Error"""
