"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import multistream_target as components_multistream_target
from ...models.errors import error as errors_error
from typing import Optional


@dataclasses.dataclass
class GetMultistreamTargetRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""ID of the multistream target"""
    



@dataclasses.dataclass
class GetMultistreamTargetResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    multistream_target: Optional[components_multistream_target.MultistreamTarget] = dataclasses.field(default=None)
    r"""Success"""
    error: Optional[errors_error.Error] = dataclasses.field(default=None)
    r"""Error"""
    

