"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer.models.components import (
    httpmetadata as components_httpmetadata,
    webhook as components_webhook,
)
from livepeer.models.errors import error as errors_error
from livepeer.types import BaseModel
import pydantic
from typing import List, Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class GetWebhooksResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    data: NotRequired[List[components_webhook.WebhookTypedDict]]
    r"""Success"""
    error: NotRequired[errors_error.Error]
    r"""Error"""


class GetWebhooksResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    data: Optional[List[components_webhook.Webhook]] = None
    r"""Success"""

    error: Optional[errors_error.Error] = None
    r"""Error"""
