"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer.models.components import (
    httpmetadata as components_httpmetadata,
    webhook_log as components_webhook_log,
)
from livepeer.models.errors import error as errors_error
from livepeer.types import BaseModel
from livepeer.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import List, Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class GetWebhookLogsRequestTypedDict(TypedDict):
    id: str


class GetWebhookLogsRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class GetWebhookLogsResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    data: NotRequired[List[components_webhook_log.WebhookLogTypedDict]]
    r"""Success"""
    error: NotRequired[errors_error.Error]
    r"""Error"""


class GetWebhookLogsResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    data: Optional[List[components_webhook_log.WebhookLog]] = None
    r"""Success"""

    error: Optional[errors_error.Error] = None
    r"""Error"""
