"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import webhook as components_webhook
from ...models.errors import error as errors_error
from typing import List, Optional


@dataclasses.dataclass
class GetWebhooksResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    data: Optional[List[components_webhook.Webhook]] = dataclasses.field(default=None)
    r"""Success"""
    error: Optional[errors_error.Error] = dataclasses.field(default=None)
    r"""Error"""
    

