"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer.models.components import (
    error as components_error,
    httpmetadata as components_httpmetadata,
    webhook_input as components_webhook_input,
)
from livepeer.types import BaseModel
from livepeer.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateWebhookRequestTypedDict(TypedDict):
    id: str
    webhook: components_webhook_input.WebhookInputTypedDict


class UpdateWebhookRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    webhook: Annotated[
        components_webhook_input.WebhookInput,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class UpdateWebhookResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    webhook: NotRequired[components_webhook_input.WebhookTypedDict]
    r"""Success"""
    error: NotRequired[components_error.ErrorTypedDict]
    r"""Error"""


class UpdateWebhookResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    webhook: Optional[components_webhook_input.Webhook] = None
    r"""Success"""

    error: Optional[components_error.Error] = None
    r"""Error"""
