"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer.models.components import (
    asset as components_asset,
    asset_patch_payload as components_asset_patch_payload,
    error as components_error,
    httpmetadata as components_httpmetadata,
)
from livepeer.types import BaseModel
from livepeer.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateAssetRequestTypedDict(TypedDict):
    asset_id: str
    r"""ID of the asset"""
    asset_patch_payload: components_asset_patch_payload.AssetPatchPayloadTypedDict


class UpdateAssetRequest(BaseModel):
    asset_id: Annotated[
        str,
        pydantic.Field(alias="assetId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of the asset"""

    asset_patch_payload: Annotated[
        components_asset_patch_payload.AssetPatchPayload,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class UpdateAssetResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    asset: NotRequired[components_asset.AssetTypedDict]
    r"""Success"""
    error: NotRequired[components_error.ErrorTypedDict]
    r"""Error"""


class UpdateAssetResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    asset: Optional[components_asset.Asset] = None
    r"""Success"""

    error: Optional[components_error.Error] = None
    r"""Error"""
